<?php
declare(strict_types=1);
$e=static fn(mixed $v):string=>htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8'); $c=$customer??[]; $editing=$customer!==null;
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?= $editing?'Edit':'Add' ?> customer | Triple R Gensan</title><link rel="stylesheet" href="/assets/css/app.css"><script src="/assets/js/customers.js" defer></script></head><body><header class="topbar"><a class="brand" href="/staff">Triple R Gensan</a><a href="/customers">Customers</a></header><main class="page-shell"><section class="page-heading"><div><p class="eyebrow">Customer management</p><h1><?= $editing?'Edit customer':'Add customer' ?></h1></div></section><?php if($error):?><p class="alert" role="alert"><?= $e($error) ?></p><?php endif;?>
<form class="panel admin-panel customer-form" method="post" action="<?= $editing?'/customers/update':'/customers/create' ?>" data-customer-form><input type="hidden" name="_csrf" value="<?= $e($csrfToken) ?>"><?php if($editing):?><input type="hidden" name="customer_id" value="<?= (int)$c['customer_id'] ?>"><?php endif;?>
<div class="form-grid"><label>Customer type<select name="customer_type" required><?php foreach($types as $t):?><option value="<?= $e($t) ?>"<?= ($c['customer_type']??'walk_in')===$t?' selected':'' ?>><?= $e(str_replace('_',' ',$t)) ?></option><?php endforeach;?></select></label><label>Full name<input name="full_name" maxlength="160" value="<?= $e($c['full_name']??'') ?>" required></label><label>Company name (required for corporate)<input name="company_name" maxlength="160" value="<?= $e($c['company_name']??'') ?>"></label><label>Referral source (required for referral)<input name="referral_source" maxlength="160" value="<?= $e($c['referral_source']??'') ?>"></label>
<?php if(!$editing):?><label>Phone (optional)<input name="phone" type="tel" maxlength="40" autocomplete="tel"></label><label>Email (optional)<input name="email" type="email" maxlength="254" autocomplete="email"></label><label>Identity document type<select name="document_type"><option value="">None</option><?php foreach($documentTypes as $docType):?><option value="<?= $e($docType) ?>"><?= $e(str_replace('_',' ',$docType)) ?></option><?php endforeach;?></select></label><label>Document number<input name="document_number" maxlength="100" autocomplete="off"></label><label>Document expiry<input type="date" name="expires_on"></label><?php endif;?></div>
<p class="muted">Phone, email, and identity numbers are encrypted in storage. Customer records do not create login accounts.</p><div class="form-actions"><button type="submit"><?= $editing?'Save customer':'Create customer' ?></button><a href="/customers">Cancel</a></div></form></main></body></html>
