<?php declare(strict_types=1);$e=static fn(mixed $v):string=>htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');$role=$user['role'];$s=$agreement['status'];$canOps=in_array($role,['system_admin','front_desk'],true);$canTrip=in_array($role,['system_admin','front_desk','fleet_manager'],true);$canFinance=in_array($role,['system_admin','finance_staff'],true);$canDriver=in_array($role,['system_admin','front_desk','driver_coordinator'],true); ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Agreement #<?= (int)$agreement['agreement_id'] ?> | Triple R Gensan</title><link rel="stylesheet" href="/assets/css/app.css"><script src="/assets/js/rentals.js" defer></script></head><body><header class="topbar"><a class="brand" href="/staff">Triple R Gensan</a><nav class="staff-actions"><a href="/rentals">Agreements</a><a href="/staff/notifications">Notifications</a></nav></header><main class="page-shell"><section class="page-heading"><div><p class="eyebrow">Rental agreement #<?= (int)$agreement['agreement_id'] ?></p><h1><?= $e($agreement['customer_name']) ?> · <?= $e($agreement['plate_number']) ?></h1><p>Status <strong><?= $e($s) ?></strong> · <?= $e($agreement['start_date']) ?> to <?= $e($agreement['end_date']) ?> · <?= (int)$agreement['rental_days'] ?> day(s)</p></div></section><?php if($notice):?><p class="alert" role="status"><?= $e($notice) ?></p><?php endif;?><section class="panel"><h2>Cost summary</h2><p>Base ₱<?= $e($agreement['base_amount']) ?> · Charges/discounts ₱<?= $e(number_format((float)$total-(float)$agreement['base_amount'],2)) ?> · Billable total ₱<?= $e($total) ?></p><p>Deposit ₱<?= $e($agreement['security_deposit_amount']) ?> — <?= $e($agreement['deposit_status']) ?></p><p>Pickup <?= $e($agreement['scheduled_pickup_at']??'not set') ?> UTC · return <?= $e($agreement['scheduled_return_at']??'not set') ?> UTC</p><?php if($canOps):?><form method="post" action="/rentals/link"><input type="hidden" name="_csrf" value="<?= $e($csrfToken) ?>"><input type="hidden" name="agreement_id" value="<?= (int)$agreement['agreement_id'] ?>"><button type="submit">Send booking-management link</button></form><?php endif;?></section>
</section>
<?php if($agreement['rental_type']==='chauffeur'):?>
<section class="panel">
    <h2>Driver Assignment</h2>
    <p>Assigned driver: <strong><?= $agreement['driver_id'] ? $e($agreement['driver_name'] ?? '') : 'None' ?></strong></p>
    <?php if($canDriver && in_array($s, ['reserved','confirmed'], true)):?>
        <form method="post" action="/rentals/driver/assign" class="form-grid">
            <input type="hidden" name="_csrf" value="<?= $e($csrfToken) ?>">
            <input type="hidden" name="agreement_id" value="<?= (int)$agreement['agreement_id'] ?>">
            <label>Driver
                <select name="driver_id" required>
                    <option value="">Select a driver</option>
                    <?php foreach($drivers??[] as $d):?>
                        <option value="<?= (int)$d['driver_id'] ?>"<?= (string)($agreement['driver_id']??'')===(string)$d['driver_id']?' selected':'' ?>><?= $e($d['full_name']) ?></option>
                    <?php endforeach;?>
                </select>
            </label>
            <button><?= $agreement['driver_id'] ? 'Reassign driver' : 'Assign driver' ?></button>
        </form>
        <?php if($agreement['driver_id'] !== null && $s === 'reserved'):?>
            <form method="post" action="/rentals/driver/remove" style="margin-top: 1rem">
                <input type="hidden" name="_csrf" value="<?= $e($csrfToken) ?>">
                <input type="hidden" name="agreement_id" value="<?= (int)$agreement['agreement_id'] ?>">
                <button type="submit" style="background:var(--error-light);color:var(--error-dark);border:none;">Remove driver</button>
            </form>
        <?php endif;?>
    <?php endif;?>
</section>
<?php endif;?>
<section class="panel"><h2>Lifecycle</h2><div class="button-row"><?php if($canOps&&$s==='reserved'):?><form method="post" action="/rentals/action"><input type="hidden" name="_csrf" value="<?= $e($csrfToken) ?>"><input type="hidden" name="agreement_id" value="<?= (int)$agreement['agreement_id'] ?>"><input type="hidden" name="action" value="confirm"><button>Confirm</button></form><?php endif;?><?php if($canTrip&&$s==='confirmed'):?><form method="post" action="/rentals/action"><input type="hidden" name="_csrf" value="<?= $e($csrfToken) ?>"><input type="hidden" name="agreement_id" value="<?= (int)$agreement['agreement_id'] ?>"><input type="hidden" name="action" value="pickup"><button>Record pickup</button></form><?php endif;?><?php if($canTrip&&$s==='active'):?><form method="post" action="/rentals/action"><input type="hidden" name="_csrf" value="<?= $e($csrfToken) ?>"><input type="hidden" name="agreement_id" value="<?= (int)$agreement['agreement_id'] ?>"><input type="hidden" name="action" value="return"><button>Record return</button></form><?php endif;?><?php if($canFinance&&$s==='returned'):?><form method="post" action="/rentals/action"><input type="hidden" name="_csrf" value="<?= $e($csrfToken) ?>"><input type="hidden" name="agreement_id" value="<?= (int)$agreement['agreement_id'] ?>"><input type="hidden" name="action" value="complete"><button>Complete after reconciliation</button></form><?php endif;?><?php if($canOps&&in_array($s,['reserved','confirmed'],true)):?><form method="post" action="/rentals/action" class="reason-action"><input type="hidden" name="_csrf" value="<?= $e($csrfToken) ?>"><input type="hidden" name="agreement_id" value="<?= (int)$agreement['agreement_id'] ?>"><input type="hidden" name="action" value="cancel"><label>Cancellation reason<input name="reason" maxlength="500" required></label><button>Cancel</button></form><?php if($agreement['scheduled_pickup_at']!==null):?><form method="post" action="/rentals/action" class="reason-action"><input type="hidden" name="_csrf" value="<?= $e($csrfToken) ?>"><input type="hidden" name="agreement_id" value="<?= (int)$agreement['agreement_id'] ?>"><input type="hidden" name="action" value="no_show"><label>No-show reason<input name="reason" maxlength="500" required></label><button>Mark no-show</button></form><?php endif;?><?php endif;?></div><h3>Agreement history</h3><div class="table-wrap"><table><thead><tr><th>UTC timestamp</th><th>From</th><th>To</th><th>Reason</th><th>Actor</th></tr></thead><tbody><?php foreach($statusHistory as $h):?><tr><td><?= $e($h['created_at']) ?></td><td><?= $e($h['old_status']??'—') ?></td><td><?= $e($h['new_status']) ?></td><td><?= $e($h['reason']??'—') ?></td><td><?= $e($h['actor_email']) ?></td></tr><?php endforeach;?></tbody></table></div><p class="muted">Return condition and damage capture belong to M7. Overdue active rentals remain active and are surfaced in M10 reporting.</p></section>
<section class="panel"><h2>Damage inspections</h2><p>Inspection facts and evidence are append-only. Pre and post each allow one report; during-rental reports may repeat.</p>
<?php if(in_array($role,['front_desk','fleet_manager'],true)):?><form method="post" action="/rentals/damage/report" enctype="multipart/form-data" class="form-grid"><input type="hidden" name="_csrf" value="<?= $e($csrfToken) ?>"><input type="hidden" name="agreement_id" value="<?= (int)$agreement['agreement_id'] ?>"><label>Phase<select name="phase"><option value="pre">Pre-rental</option><option value="during">During rental</option><option value="post">Post-rental</option></select></label><label>Damage found?<select name="has_damage"><option value="0">No damage</option><option value="1">Yes</option></select></label><label>Location<input name="location" maxlength="120" placeholder="e.g. left rear door"></label><label>Damage type<input name="damage_type" maxlength="40" placeholder="e.g. dent"></label><label>Severity<select name="severity"><option value="">Choose if damage found</option><option value="minor">Minor</option><option value="moderate">Moderate</option><option value="severe">Severe</option></select></label><label>Repair cost suggestion (₱)<input name="repair_cost_suggestion" type="number" min="0" step="0.01"></label><label>Notes<input name="notes" maxlength="1000"></label><label>Photos (JPEG, PNG, WebP; max 8 MB each)<input name="photos[]" type="file" accept="image/jpeg,image/png,image/webp" multiple></label><button>Record inspection</button></form><?php endif;?>
<?php foreach($damageReports as $dr):?><article class="panel"><h3><a href="/rentals/damage/detail?report_id=<?= (int)$dr['report_id'] ?>"><?= $e(strtoupper($dr['phase'])) ?> inspection · <?= $dr['has_damage']?'Damage reported':'No damage reported' ?></a></h3><p><?= $e($dr['created_at']) ?> · <?= $e($dr['recorded_by_email']) ?><?php if($dr['has_damage']):?> · <?= $e($dr['location']) ?> · <?= $e($dr['damage_type']) ?> · <?= $e($dr['severity']) ?> · suggested ₱<?= $e($dr['repair_cost_suggestion']??'—') ?><?php endif;?></p><?php if($dr['notes']):?><p><?= $e($dr['notes']) ?></p><?php endif;?><?php foreach($dr['photos'] as $photo):?><a href="/rentals/damage/photo?photo_id=<?= (int)$photo['photo_id'] ?>" target="_blank" rel="noopener"><?= $e($photo['original_filename']) ?></a> · <?php endforeach;?>
<?php if($dr['has_damage']&&in_array($role,['fleet_manager','system_admin'],true)):?><h4><?= $dr['decision_id']?'Current liability decision':'Record liability decision' ?></h4><?php if($dr['decision_id']):?><p><?= $dr['customer_liable']?'Customer liable':'Customer not liable' ?> · ₱<?= $e($dr['liable_amount']) ?> · <?= $e($dr['liability_reason']) ?> · <?= $e($dr['decided_at']) ?></p><?php endif;?><form method="post" action="/rentals/damage/liability" class="form-grid"><input type="hidden" name="_csrf" value="<?= $e($csrfToken) ?>"><input type="hidden" name="agreement_id" value="<?= (int)$agreement['agreement_id'] ?>"><input type="hidden" name="report_id" value="<?= (int)$dr['report_id'] ?>"><input type="hidden" name="supersedes_decision_id" value="<?= (int)($dr['decision_id']??0) ?: '' ?>"><label>Finding<select name="customer_liable"><option value="1">Customer liable</option><option value="0">Customer not liable</option></select></label><label>Liable amount (₱)<input name="liable_amount" type="number" min="0" step="0.01" value="<?= $e($dr['decision_id']?$dr['liable_amount']:($dr['repair_cost_suggestion']??'0')) ?>" required></label><label>Reason / correction reason<input name="reason" maxlength="1000" required></label><button><?= $dr['decision_id']?'Supersede decision':'Record decision' ?></button></form><?php endif;?>
<?php if($dr['decision_id']&&(int)$dr['customer_liable']===1&&$role==='finance_staff'):?><form method="post" action="/rentals/damage/charge" class="form-grid"><input type="hidden" name="_csrf" value="<?= $e($csrfToken) ?>"><input type="hidden" name="agreement_id" value="<?= (int)$agreement['agreement_id'] ?>"><input type="hidden" name="decision_id" value="<?= (int)$dr['decision_id'] ?>"><label>Approved damage charge (₱)<input name="amount" type="number" min="0.01" max="<?= $e($dr['liable_amount']) ?>" step="0.01" value="<?= $e($dr['liable_amount']) ?>" required></label><label>Adjustment reason<input name="adjustment_reason" maxlength="500"></label><button>Post damage charge</button></form><?php endif;?></article><?php endforeach;?>
</section>
<section class="panel"><h2>Charges</h2><div class="table-wrap"><table><thead><tr><th>Type</th><th>Entry</th><th>Amount</th><th>Description</th><th>When / by</th><th></th></tr></thead><tbody><?php foreach($charges as $c):?><tr><td><?= $e($c['charge_type']) ?></td><td><?= $e($c['entry_kind']) ?></td><td>₱<?= $e($c['amount']) ?></td><td><?= $e($c['description']) ?></td><td><?= $e($c['created_at'].' / '.$c['actor_email']) ?></td><td><?php if($canFinance&&$c['entry_kind']==='charge'):?><form method="post" action="/rentals/charge/reverse" class="inline-form"><input type="hidden" name="_csrf" value="<?= $e($csrfToken) ?>"><input type="hidden" name="agreement_id" value="<?= (int)$agreement['agreement_id'] ?>"><input type="hidden" name="charge_id" value="<?= (int)$c['charge_id'] ?>"><input name="reason" maxlength="490" placeholder="Reversal reason" required><button>Reverse</button></form><?php endif;?></td></tr><?php endforeach;?><?php if(!$charges):?><tr><td colspan="6">No additional charges.</td></tr><?php endif;?></tbody></table></div><?php if($canFinance&&!in_array($s,['completed','cancelled','no_show'],true)):?><form method="post" action="/rentals/charge" class="form-grid"><input type="hidden" name="_csrf" value="<?= $e($csrfToken) ?>"><input type="hidden" name="agreement_id" value="<?= (int)$agreement['agreement_id'] ?>"><label>Type<select name="charge_type"><option>fee</option><option>discount</option><option>tax</option><option>damage</option><option>other</option></select></label><label>Amount (₱)<input name="amount" type="number" min="0.01" step="0.01" required></label><label>Description<input name="description" maxlength="500" required></label><button>Add charge</button></form><?php endif;?></section>
<section class="panel"><h2>Deposit history</h2><div class="table-wrap"><table><thead><tr><th>UTC</th><th>From</th><th>To</th><th>Amount</th><th>Reason</th><th>Actor</th></tr></thead><tbody><?php foreach($depositHistory as $d):?><tr><td><?= $e($d['created_at']) ?></td><td><?= $e($d['old_status']??'—') ?></td><td><?= $e($d['new_status']) ?></td><td><?= $e($d['old_amount']??'—') ?> → <?= $e($d['new_amount']) ?></td><td><?= $e($d['reason']) ?></td><td><?= $e($d['actor_email']) ?></td></tr><?php endforeach;?></tbody></table></div><?php if($canFinance&&!in_array($s,['completed','cancelled','no_show'],true)):?><form method="post" action="/rentals/deposit" class="form-grid"><input type="hidden" name="_csrf" value="<?= $e($csrfToken) ?>"><input type="hidden" name="agreement_id" value="<?= (int)$agreement['agreement_id'] ?>"><label>Deposit status<select name="deposit_status"><?php foreach(['not_required','due','held','released','refunded','forfeited'] as $ds):?><option value="<?= $e($ds) ?>"<?= $agreement['deposit_status']===$ds?' selected':'' ?>><?= $e($ds) ?></option><?php endforeach;?></select></label><label>Amount (₱)<input name="amount" type="number" min="0" step="0.01" value="<?= $e($agreement['security_deposit_amount']) ?>" required></label><label>Reason<input name="reason" maxlength="500" required></label><button>Record deposit change</button></form><?php endif;?></section></main></body></html>
