<?php
declare(strict_types=1);
$e=static fn(mixed $v):string=>htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');
$superseded=array_map('intval',array_filter(array_column($mileageHistory,'correction_of_log_id')));
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?= $e($vehicle['plate_number']) ?> | Triple R Gensan</title><link rel="stylesheet" href="/assets/css/app.css"><script src="/assets/js/vehicles.js" defer></script></head><body><header class="topbar"><a class="brand" href="/staff">Triple R Gensan</a><nav class="staff-actions"><a href="/fleet/vehicles">Fleet</a><a href="/fleet/locations">Locations</a><a href="/staff/notifications">Notifications</a></nav></header><main class="page-shell">
<section class="page-heading"><div><p class="eyebrow">Vehicle details</p><h1><?= $e($vehicle['plate_number']) ?> — <?= $e($vehicle['model_year'].' '.$vehicle['make'].' '.$vehicle['model']) ?></h1><p>Status: <strong><?= $e($vehicle['current_status']) ?></strong> · <?= $e($vehicle['current_mileage']) ?> km · Location: <?= $e($vehicle['location_name']??'Not recorded') ?></p></div><?php if($vehicle['deleted_at']===null):?><a class="button-link" href="/fleet/vehicles/edit?vehicle_id=<?= (int)$vehicle['vehicle_id'] ?>">Edit vehicle</a><?php endif;?></section>
<?php if($notice):?><p class="alert" role="status"><?= $e($notice) ?></p><?php endif;?>
<section class="panel"><div class="panel-heading"><h2>Specifications and documents</h2></div><dl class="vehicle-specs"><?php foreach(['engine_number'=>'Engine no.','chassis_number'=>'Chassis no.','color'=>'Color','body_type'=>'Body type','transmission'=>'Transmission','fuel_type'=>'Fuel type','seating_capacity'=>'Seats','daily_rate'=>'Daily rate','chauffeur_daily_rate'=>'Chauffeur daily rate','registration_expiry'=>'Registration expiry','insurance_expiry'=>'Insurance expiry','insurance_provider'=>'Insurance provider','notes'=>'Notes'] as $key=>$label):?><div><dt><?= $e($label) ?></dt><dd><?= $e($vehicle[$key]??'—') ?: '—' ?></dd></div><?php endforeach;?></dl></section>
<section class="panel"><div class="panel-heading"><h2>Photos</h2></div><?php if($vehicle['deleted_at']===null):?><form method="post" action="/fleet/vehicles/photos/upload" enctype="multipart/form-data"><input type="hidden" name="_csrf" value="<?= $e($csrfToken) ?>"><input type="hidden" name="vehicle_id" value="<?= (int)$vehicle['vehicle_id'] ?>"><label>JPEG, PNG, or WebP (max 8 MB) <input type="file" name="photo" accept="image/jpeg,image/png,image/webp" required></label><button type="submit">Upload photo</button></form><?php endif;?><div class="photo-grid"><?php foreach($photos as $photo):?><figure><img src="/fleet/vehicles/photos/show?photo_id=<?= (int)$photo['photo_id'] ?>" alt="<?= $e($photo['original_filename']) ?>"><figcaption><?= $e($photo['original_filename']) ?></figcaption></figure><?php endforeach;?><?php if(!$photos):?><p>No photos uploaded.</p><?php endif;?></div></section>
<section class="panel"><div class="panel-heading"><h2>Status history</h2></div><?php if($vehicle['deleted_at']===null):?><form class="inline-form" method="post" action="/fleet/vehicles/status" data-confirm="Record this vehicle status transition?"><input type="hidden" name="_csrf" value="<?= $e($csrfToken) ?>"><input type="hidden" name="vehicle_id" value="<?= (int)$vehicle['vehicle_id'] ?>"><label>New status<select name="status" required><?php foreach($statuses as $s):if($s!==$vehicle['current_status']):?><option value="<?= $e($s) ?>"><?= $e(str_replace('_',' ',$s)) ?></option><?php endif;endforeach;?></select></label><button type="submit">Record transition</button></form><?php else:?><p class="muted">Retired vehicle. History is retained read-only.</p><?php endif;?><div class="table-wrap"><table><thead><tr><th>When (UTC)</th><th>Old</th><th>New</th><th>Location</th><th>Mileage</th><th>By</th></tr></thead><tbody><?php foreach($statusHistory as $h):?><tr><td><?= $e($h['created_at']) ?></td><td><?= $e($h['old_status']??'—') ?></td><td><?= $e($h['new_status']) ?></td><td><?= $e($h['location_name']??'—') ?></td><td><?= $e($h['mileage']??'—') ?></td><td><?= $e($h['actor_email']) ?></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="panel"><div class="panel-heading"><h2>Odometer readings</h2><p>Readings can be recorded independently of status changes. Corrections require system_admin and remain in the append-only history.</p></div><?php if($vehicle['deleted_at']===null):?><form method="post" action="/fleet/vehicles/mileage" class="form-grid"><input type="hidden" name="_csrf" value="<?= $e($csrfToken) ?>"><input type="hidden" name="vehicle_id" value="<?= (int)$vehicle['vehicle_id'] ?>"><label>Mileage (km)<input type="number" min="0" step="1" name="mileage" required></label><label>Location<select name="location_id"><option value="">No location change</option><?php foreach($locations as $loc):?><option value="<?= (int)$loc['location_id'] ?>"><?= $e($loc['name']) ?></option><?php endforeach;?></select></label><button type="submit">Record reading</button></form>
<?php if($user['role']==='system_admin'):?><form method="post" action="/fleet/vehicles/mileage" class="form-grid correction-form"><input type="hidden" name="_csrf" value="<?= $e($csrfToken) ?>"><input type="hidden" name="vehicle_id" value="<?= (int)$vehicle['vehicle_id'] ?>"><label>Correct entry<select name="corrects_log_id" required><option value="">Choose a reading/correction chain head</option><?php foreach($mileageHistory as $m):if(!in_array((int)$m['mileage_log_id'],$superseded,true)):?><option value="<?= (int)$m['mileage_log_id'] ?>">#<?= (int)$m['mileage_log_id'] ?> — <?= $e($m['mileage']) ?> km, <?= $e($m['recorded_at']) ?><?= $m['correction_of_log_id']?' (correction)':'' ?></option><?php endif;endforeach;?></select></label><label>Corrected mileage (km)<input type="number" min="0" step="1" name="mileage" required></label><label>Reason<input name="correction_reason" maxlength="500" required></label><button type="submit">Append correction</button></form><?php endif;?><?php else:?><p class="muted">Retired vehicle. Mileage history is read-only.</p><?php endif;?>
<div class="table-wrap"><table><thead><tr><th>When (UTC)</th><th>Reading</th><th>Location</th><th>Correction of</th><th>Reason</th><th>By</th></tr></thead><tbody><?php foreach($mileageHistory as $m):?><tr><td><?= $e($m['recorded_at']) ?></td><td><?= $e($m['mileage']) ?> km</td><td><?= $e($m['location_name']??'—') ?></td><td><?= $e($m['correction_of_log_id']??'—') ?></td><td><?= $e($m['correction_reason']??'—') ?></td><td><?= $e($m['actor_email']) ?></td></tr><?php endforeach;?></tbody></table></div></section></main></body></html>
