<?php
declare(strict_types=1);
$e=static fn(mixed $v):string=>htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8'); $v=$vehicle??[]; $editing=$vehicle!==null;
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?= $editing?'Edit':'Register' ?> vehicle | Triple R Gensan</title><link rel="stylesheet" href="/assets/css/app.css"><script src="/assets/js/vehicles.js" defer></script></head><body><header class="topbar"><a class="brand" href="/staff">Triple R Gensan</a><a href="/fleet/vehicles">Vehicle fleet</a></header><main class="page-shell"><section class="page-heading"><div><p class="eyebrow">Fleet management</p><h1><?= $editing?'Edit vehicle':'Register vehicle' ?></h1></div></section>
<?php if($error):?><p class="alert" role="alert"><?= $e($error) ?></p><?php endif;?>
<form class="panel admin-panel vehicle-form" method="post" action="<?= $editing?'/fleet/vehicles/update':'/fleet/vehicles/create' ?>" data-vehicle-form><input type="hidden" name="_csrf" value="<?= $e($csrfToken) ?>"><?php if($editing):?><input type="hidden" name="vehicle_id" value="<?= (int)$v['vehicle_id'] ?>"><?php endif;?>
<div class="form-grid">
<?php $fields=[['plate_number','Plate number',20],['engine_number','Engine number',80],['chassis_number','Chassis number',80],['make','Make',60],['model','Model',80],['model_year','Model year',5],['color','Color',40],['seating_capacity','Seating capacity',3],['daily_rate','Daily rate (₱)',10],['chauffeur_daily_rate','Chauffeur daily rate (₱; blank means unavailable)',10],['insurance_provider','Insurance provider',80]]; foreach($fields as [$key,$label,$max]):?><label><?= $e($label) ?><input name="<?= $e($key) ?>" maxlength="<?= (int)$max ?>" value="<?= $e($v[$key]??'') ?>"<?= in_array($key,['plate_number','make','model','model_year','color','seating_capacity','daily_rate'],true)?' required':'' ?><?= in_array($key,['model_year','seating_capacity'],true)?' type="number" min="1"':(str_contains($key,'rate')?' type="number" min="0" step="0.01"':'') ?>></label><?php endforeach;?>
<label>Current mileage (km)<input name="current_mileage" type="number" min="0" step="1" value="<?= $e($v['current_mileage']??0) ?>" required<?= $editing?' readonly':'' ?>></label>
<label>Body type<select name="body_type" required><?php foreach(['sedan','SUV','van','pickup','hatchback'] as $x):?><option value="<?= $e($x) ?>"<?= ($v['body_type']??'')===$x?' selected':'' ?>><?= $e($x) ?></option><?php endforeach;?></select></label>
<label>Transmission<select name="transmission" required><?php foreach(['manual','automatic'] as $x):?><option value="<?= $e($x) ?>"<?= ($v['transmission']??'')===$x?' selected':'' ?>><?= $e($x) ?></option><?php endforeach;?></select></label>
<label>Fuel type<select name="fuel_type" required><?php foreach(['gasoline','diesel','hybrid'] as $x):?><option value="<?= $e($x) ?>"<?= ($v['fuel_type']??'')===$x?' selected':'' ?>><?= $e($x) ?></option><?php endforeach;?></select></label>
<?php foreach(['registration_expiry'=>'Registration expiry','insurance_expiry'=>'Insurance expiry'] as $key=>$label):?><label><?= $e($label) ?><input type="date" name="<?= $e($key) ?>" value="<?= $e($v[$key]??'') ?>"></label><?php endforeach;?>
<label class="wide-field">Notes<textarea name="notes" rows="4"><?= $e($v['notes']??'') ?></textarea></label></div><p class="muted">Engine and chassis numbers may be left blank while documents are pending. Weekly and monthly rates are not stored.</p><div class="form-actions"><button type="submit"><?= $editing?'Save changes':'Register vehicle' ?></button><a href="/fleet/vehicles">Cancel</a></div></form></main></body></html>
