<?php
declare(strict_types=1);
$e=static fn(mixed $v):string=>htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8'); $editing=$driver!==null; $d=$driver??[];
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?= $editing?'Edit':'Add' ?> driver | Triple R Gensan</title><link rel="stylesheet" href="/assets/css/app.css"><script src="/assets/js/drivers.js" defer></script></head><body>
<header class="topbar"><a class="brand" href="/staff">Triple R Gensan</a><a href="/fleet/drivers">Drivers</a></header><main class="page-shell"><section class="page-heading"><div><p class="eyebrow">Fleet management</p><h1><?= $editing?'Edit driver':'Add driver' ?></h1></div></section><?php if($error):?><p class="alert" role="alert"><?= $e($error) ?></p><?php endif;?>
<form class="panel admin-panel form-grid" method="post" action="<?= $editing?'/fleet/drivers/update':'/fleet/drivers/create' ?>" data-driver-form><input type="hidden" name="_csrf" value="<?= $e($csrfToken) ?>"><?php if($editing):?><input type="hidden" name="driver_id" value="<?= (int)$d['driver_id'] ?>"><?php endif;?>
<label>Full name<input name="full_name" maxlength="160" value="<?= $e($d['full_name']??'') ?>" required></label><label>License number<input name="license_number" maxlength="100" <?= $editing?'placeholder="Leave blank to keep the current encrypted value"':'required' ?> autocomplete="off"></label><label>License expiry<input type="date" name="license_expiry" value="<?= $e($d['license_expiry']??'') ?>" required></label>
<?php if(!$editing):?><label>Phone<input type="tel" name="phone" maxlength="40" autocomplete="tel"></label><label>Email<input type="email" name="email" maxlength="254" autocomplete="email"></label><?php endif;?>
<label>Address<textarea name="address" rows="2" maxlength="1000" placeholder="<?= $editing&&$d['address_ciphertext']!==null?'Leave blank to keep the encrypted address':'' ?>"></textarea></label><?php if($editing&&$d['address_ciphertext']!==null):?><label class="check-label"><input type="checkbox" name="clear_address" value="1"> Clear saved address</label><?php endif;?><label>Emergency contact name<input name="emergency_contact_name" maxlength="160" placeholder="<?= $editing&&$d['emergency_contact_name_ciphertext']!==null?'Leave both emergency fields blank to keep current details':'' ?>"></label><label>Emergency contact phone<input type="tel" name="emergency_contact_phone" maxlength="40"></label><?php if($editing&&$d['emergency_contact_name_ciphertext']!==null):?><label class="check-label"><input type="checkbox" name="clear_emergency_contact" value="1"> Clear emergency contact</label><?php endif;?><label>Staff notes<textarea name="notes" rows="3" maxlength="5000"><?= $e($d['notes']??'') ?></textarea></label>
<p class="muted">License, contact, address, and emergency contact values are encrypted with DRIVER_PII_KEY. Notes are searchable staff text; do not put license or contact details there.</p><div class="form-actions"><button type="submit"><?= $editing?'Save driver':'Create driver' ?></button><a href="/fleet/drivers">Cancel</a></div></form></main></body></html>
