<?php
declare(strict_types=1);
$e=static fn(mixed $v):string=>htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Drivers | Triple R Gensan</title><link rel="stylesheet" href="/assets/css/app.css"><script src="/assets/js/drivers.js" defer></script></head><body>
<header class="topbar"><a class="brand" href="/staff">Triple R Gensan</a><nav class="staff-actions"><a href="/fleet/vehicles">Vehicles</a><a href="/fleet/drivers">Drivers</a><a href="/staff/notifications">Notifications</a></nav></header>
<main class="page-shell"><section class="page-heading"><div><p class="eyebrow">Fleet management</p><h1>Drivers</h1><p>Signed in as <?= $e($user['email']) ?> (<?= $e($user['role']) ?>)</p></div><?php if($canManage):?><a class="button-link" href="/fleet/drivers/new">Add driver</a><?php endif;?></section>
<form class="panel filter-form" method="get" action="/fleet/drivers"><label>Search driver name<input name="search" value="<?= $e($search) ?>" maxlength="160"></label><button type="submit">Search</button></form>
<section class="panel"><div class="panel-heading"><h2>Driver records</h2><p>License expiry and status are visible to authorized fleet and driver-coordination staff.</p></div><div class="table-wrap"><table><thead><tr><th>Name</th><th>License</th><th>Expiry</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($drivers as $driver):?><tr><td><?= $e($driver['full_name']) ?></td><td><?= $e($driver['license_display']) ?></td><td><?= $e($driver['license_expiry']) ?></td><td><?= $e($driver['status']) ?></td><td><a href="/fleet/drivers/detail?driver_id=<?= (int)$driver['driver_id'] ?>">Details</a></td></tr><?php endforeach;?><?php if(!$drivers):?><tr><td colspan="5">No drivers found.</td></tr><?php endif;?></tbody></table></div></section>
<section class="panel"><div class="panel-heading"><h2>Eligible for a new assignment</h2><p>Active, non-deleted drivers whose license is valid through today in Asia/Manila.</p></div><div class="table-wrap"><table><thead><tr><th>Name</th><th>License expiry</th></tr></thead><tbody><?php foreach($eligibleDrivers as $driver):?><tr><td><?= $e($driver['full_name']) ?></td><td><?= $e($driver['license_expiry']) ?></td></tr><?php endforeach;?><?php if(!$eligibleDrivers):?><tr><td colspan="2">No drivers currently meet the assignment eligibility rules.</td></tr><?php endif;?></tbody></table></div></section>
</main></body></html>
